name: 📊 GitHub Metrics

on:
  schedule: [{ cron: "0 12 * * *" }]  # Daily at 12:00 UTC
  workflow_dispatch:

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - name: Generate GitHub Metrics
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }} # Your personal access token with correct scopes
          committer_token: ${{ secrets.METRICS_TOKEN }} # Token used to commit back the file
          user: gitadam0
          base: activity, community, repositories, metadata
          config_timezone: Africa/Casablanca
          plugin_lines: yes
          plugin_languages: yes
          plugin_languages_ignored: html, css
          plugin_languages_threshold: 1%
