name: 📊 GitHub Metrics

on:
  schedule: [{ cron: "0 12 * * *" }]
  workflow_dispatch:

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          user: gitadam0
          base: activity, community, repositories, metadata
          config_timezone: Africa/Casablanca
          plugin_lines: yes
          plugin_languages: yes
          plugin_languages_ignored: >-
            html, css
          plugin_languages_threshold: 1%
